### ISSUE TITLE
【機能追加】検索オプションの動的変更

### ISSUE THREAD

**Issue by witnak** [maki-tetsu/anodator#17]
# 検索オプションの動的変更

オプションの動的変更に対応してほしい。
チェック実行時に、DBなどから取り込んだ値を見て条件をある程度変更したい。

## presense

* 必須チェックの実施スイッチを追加したい。  
  Booleanで、defaultはtrue。  
  trueなら、存在チェックを実施する。  

## length

* 比較するサイズを変更できるようにしたい。

## numeric

* 上限値、下限値を変更できるようにしたい。
* 比較する値を変更できるようにしたい。

**Comment by maki-tetsu** [comment]
スイッチや変更後の値はどうやって渡しますか？
また、上記の項目はチェックデータ毎に異なりますか？共通ですか？

**Comment by witnak** [comment]
返信遅くなりすみません。
上記項目はデータチェックごとに異なります。
タイミングとしては、Anodator::Checker.new()をするタイミングになると思います。
渡し方はどうしましょうか…
例えば、こういうのはどうでしょうか。

```
value1_max = 10
value1_min = 1
value2_max = 100
value2_min = 15
input_dynamic_values =
  [
    { number: 'value1_max', value: value1_max },
    { number: 'value1_min', value: value1_min },
    { number: 'value2_max', value: value2_max },
    { number: 'value2_min', value: value2_min }
  ]
・
・
・
validator = Validator::NumericValidator.new('numeric_value', 'greater_than:{{value1_min}},less_than_or_equal_to:{{value1_max}}')
rule_set << Rule.new('numeric_value', Message.new('[[numeric_value::name]] range error .([[1::value]])'), validator)

・
・
・
### Checker
### 引数の末尾にinput_dynamic_valuesを追加する。
checker = Checker.new(input_spec, rule_set, output_spec,input_dynamic_values)
・
・
・
```
* 動的値を渡すための配列を用意します。
* [[]]でInputSpecのnumberを指定していますが、それと同じように{{}}で動的値を一意に識別するようにします。
* Checker.newで動的値を渡すための配列を渡します。

**Comment by maki-tetsu** [comment]
具体的な利用方法よりもユースケースを先に洗った方が良さそうな印象を受けました。
上記の機能だけでは、例えば外部マスターを参照して対応するデータが存在するかをチェックするような機能は実現できないのですが、このユースケースも必要そうな気がします

**Comment by maki-tetsu** [comment]
#18 で対応できることが確認できたので，本件は終了する
